### ISSUE TITLE
Running genTexData unable to read jpeg file

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#106]
<a href="https://github.com/sprlee"><img src="https://avatars1.githubusercontent.com/u/4101088?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sprlee](https://github.com/sprlee)**
_Friday Sep 01, 2017 at 08:47 GMT_
_Originally opened as https://github.com/artoolkit/artoolkit5/issues/338_

----

in libjpeg.c

  /* Initialize the JPEG decompression object with default error handling. */
166     memset(&cinfo, 0, sizeof(cinfo));
167 
168     /* We set up the normal JPEG error routines, then override error_exit. */
169     cinfo.err = jpeg_std_error(&jerr.pub);
170     jerr.pub.error_exit = my_error_exit;
171     /* Establish the setjmp return context for my_error_exit to use. */
172     if (setjmp(jerr.setjmp_buffer)) {         **====>error!!!  why????**
173         /* If we get here, the JPEG code has signaled an error.
174          * We need to clean up the JPEG object, close the input file, and return.

in centos 6.5  

build success

**Comment by ThorstenBux** [comment]
<a href="https://github.com/sprlee"><img src="https://avatars1.githubusercontent.com/u/4101088?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sprlee](https://github.com/sprlee)**
_Friday Sep 01, 2017 at 08:48 GMT_

----

@kig @tbfly @ @wallywyyoung @nanocell

**Comment by ThorstenBux** [comment]
@sprlee, sorry for the late response. Do you have any update on this? Can you please share the complete error message and the jpeg you are using?

**Comment by tyoli** [comment]
this question,me too.but when build and run it on Mac is ok.same code.

**Comment by tyoli** [comment]
I solved this problem. If you directly apt-get install libjpeg-dev under Ubuntu, if you have to use the specified libjpeg version in other Linux systems, it is possible that the correct code can not run normally. The problem is on one of the structures in the code.

**Comment by benjstern** [comment]
I'm getting this Issue on Windows as well are there any workarounds/recommendations for fixing this?

**Comment by benjstern** [comment]
From what i understand it should be compiled into the code lib and headers reference link is: https://windows.php.net/downloadS/php-sdk/deps/vc15/x86/ with filename: libjpeg-9b-vc15-x86

**Comment by slowizzm** [comment]
I just came across this issue on mac last night, using the genTexData from artoolkit/artoolkit5 repo worked for me.

**Comment by ThorstenBux** [comment]
@benjstern @slowizzm I'm not sure if you need to compile genTexData yourself. You can download the precompiled windows package from http://www.artoolkitx.org/docs/downloads/ inside SDK/bin you can find the precompiled tools and everything. For me these versions are working on Windows 10.

Let me know if you have the need to compile the tools yourself. Then I'll start to investigate why it fails for you because our continuous delivery system successfully builds the tools on a Windows box.

**Comment by ThorstenBux** [comment]
@slowizzm many thanks for that. I'm just pointing out that everyone can get the up to date versions of the tools from the artoolkitx.org/downloads packages as I'm unsure about the actuality of the versions from other sources.
