### ISSUE TITLE
Calibration of an iOS device

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#107]
<a href="https://github.com/gilduz"><img src="https://avatars2.githubusercontent.com/u/1778733?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gilduz](https://github.com/gilduz)**
_Monday Sep 11, 2017 at 14:41 GMT_
_Originally opened as https://github.com/artoolkit/artoolkit5/issues/339_

----

Dear all,
I'm trying to evaluate the accuracy of ARToolkit for relative pose estimation between 2 markers using an iPad Mini first generation. Calibration parameters for this particular device are not included in SDK. Is there a way to estimate these parameter using the calibration procedure? I found an Android application to calibrate camera but not the iOS one. Would be great if there is the ability to do this using calib_camera on a macbook via OSX library, feeding it with pictures taken with iPad.

Thank you in advance

**Comment by ThorstenBux** [comment]
@gilduz here you can find the code for the camera calibration that should compile for you device:

https://github.com/artoolkit/artoolkit6-calibration

**Comment by PierreFritsch** [comment]
Thanks for sharing the source code of the ARToolKit6 calibration app, @ThorstenBux.

Hints to others landing here:
* To compile, the calibration app [depends on the ARToolKit6 library](https://github.com/artoolkit/artoolkit6-calibration/issues/2).
* I couldn't find the calibration app on the Apple App Store (neither for iOS, nor for macOS).

**Comment by philip-lamb** [comment]
This is an old issue. Calibration app with only dependency on artoolkitX is now here: https://github.com/artoolkitx/artoolkitx-calibration
