### ISSUE TITLE
cube need to drawn at the center of the page's coordinate system. 

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#113]
<a href="https://github.com/chtngtr"><img src="https://avatars1.githubusercontent.com/u/20681153?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chtngtr](https://github.com/chtngtr)**
_Monday Oct 23, 2017 at 07:47 GMT_
_Originally opened as https://github.com/artoolkit/artoolkit5/issues/349_

----

Hi All, I am new to artoolkit, I am using artoolkit5.3.2.
Currently the on android/IOS nftSimple example, Once the image is recognized, the color cube will be drawn at the origin of the page's coordinate system. 

Can anyone please tell how to render cube at the center of the trackable image(pinball).

Any help would be greatly appreciable.
Thanks in advance.

**Comment by ThorstenBux** [comment]
<a href="https://github.com/chtngtr"><img src="https://avatars1.githubusercontent.com/u/20681153?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chtngtr](https://github.com/chtngtr)**
_Thursday Nov 02, 2017 at 12:55 GMT_

----

Can anyone please tell how to render cube at the center, I am waiting for reply.

Any help would be greatly appreciable.
Thanks in advance.

**Comment by ThorstenBux** [comment]
That function, in detail the function to get the center point of an NFT trackable is not part of ARToolKit5 at the moment.
You would need to use the input image and get its width and height. Then map that to the actual size of the image in the video stream and from there calculate the center.

**Comment by mohdsaleem987** [comment]
hello Sir,
Hi All, I am new to artoolkit, I am using artoolkit5.3.2.
I am import nftSimple project in android studio but the project is not working
Please tell me the problems

**Comment by ThorstenBux** [comment]
Please provide a logcat output of the start of your app and open a new issue, thanks
