### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#128]
<a href="https://github.com/ankitsevakhr"><img src="https://avatars3.githubusercontent.com/u/7479235?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ankitsevakhr](https://github.com/ankitsevakhr)**
_Tuesday Dec 19, 2017 at 06:13 GMT_
_Originally opened as https://github.com/artoolkit/artoolkit5/issues/368_

----

Example ARSimpleNativeCarsProj (Android Studio)

JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring

from boolean org.artoolkit.ar.base.NativeInterface.arwStartRunning(java.lang.String, java.lang.String, float, float)

**Comment by ThorstenBux** [comment]
I've fixed some things and merged back to master. Let me know if the issue still persists.
@O-O-Balance
@ankitsevakhr

**Comment by qingchengnus** [comment]
This issue still persists on master branch.

**Comment by ThorstenBux** [comment]
Please check artoolkitX https://github.com/artoolkitx/artoolkit5
