### ISSUE TITLE
Error when running the AR-Toolkit iOS example projects

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#133]
<a href="https://github.com/njanirudh"><img src="https://avatars3.githubusercontent.com/u/15691827?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [njanirudh](https://github.com/njanirudh)**
_Wednesday Jan 03, 2018 at 05:07 GMT_
_Originally opened as https://github.com/artoolkit/artoolkit5/issues/374_

----

I am trying to run AR-Toolkit examples given by the **5.3.2-iOS SDK** (http://archive.artoolkit.org/dist/artoolkit5/5.3/ARToolKit5-bin-5.3.2-iOS.tar.gz).      
On opening the project in XCode i was getting the configuration error.

![](https://user-images.githubusercontent.com/15691827/34509556-274c00b4-f071-11e7-9874-e688fd129e3d.png?raw=true)

MAC Configuration     
macOS Sierra (10.12.6)
XCode   7.3 , 8.3.3 and 9.2    

Any idea how to solve this error?

**Comment by ThorstenBux** [comment]
@njanirudh is it working when you use the master from this fork or the package form artoolkitx.org?

**Comment by njanirudh** [comment]
I am using the package from the website

**Comment by ThorstenBux** [comment]
I don't understand from which website are you using the package? And which version number does it show?
