### ISSUE TITLE
Programmatical generation of patt files for custom markers

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#145]
Original from @siddhartpai; https://github.com/artoolkit/artoolkit5/issues/389

HiI tried generating patt files by using the mk_patt utility present on the SDK, Is there some way where I can generate a custom marker by providing an input image to AR Toolkit and generating patts based on that ?ThanksSiddharth
--

**Comment by ThorstenBux** [comment]
Yes you can use the genMarkerSet executable

**Comment by siddhartpai** [comment]
How do i automate the genMarkerSet so that i don't need to  configure the labelling mode and auto save the pattern file?

**Comment by ThorstenBux** [comment]
Well, that is for you to implement. Have a look at the source and go from there

**Comment by siddhartpai** [comment]
Okay Thanks, I'll look into it .
