### ISSUE TITLE
Android camera calibration .dat file not readable

### ISSUE THREAD

**Issue by cyberbaze** [artoolkitx/artoolkit5#147]
As posted on the reviews on the play store:
The .dat file with the calibration seems to be an unknown binary format, not the text-based format

[camera_para-samsung_SM-G920F_universal7420-0-640x480.zip](https://github.com/artoolkitx/artoolkit5/files/1754727/camera_para-samsung_SM-G920F_universal7420-0-640x480.zip)

**Comment by philip-lamb** [comment]
ARToolKit has always used a binary format for the camera calibrations. You can see how it is written by looking at the file arParamSave.c in libAR.
