### ISSUE TITLE
AR not working on certain Android devices

### ISSUE THREAD

**Issue by O-O-Balance** [artoolkitx/artoolkit5#148]
Moved here from [artoolkit5](https://github.com/artoolkit/artoolkit5/issues/392).

I am developing an Android app with ARToolKit and for the most part, things are working great. On one particular test device however (a Motorola Moto G5), ARToolKit will not start. The error message is:

`E/libAR: [error] returned error code "-1" starting video capture.`

And further down:

```
I/libAR: [info] Closing ARToolKit video.
E/libAR: [error] Error: cannot close video while frames are still being pushed.
E/libAR: [error] Error closing video.
E/libAR: [error] ARController::androidVideoPush1: ARVideoSource is not running.
```

Since switching to ARToolKitX, I have been initializing ARToolKit like this

`toolkit.startWithPushedVideo(width, height, "NV21", camera_parameters_path, 0, false);`

and I wonder whether it's something to do with that since I had to work out the `"NV21"` part by trial and error. It may however be unrelated.
Any advice would be greatly appreciated.

**Comment by ThorstenBux** [comment]
Can you run the simple example from artoolkitX project on your Moto G5

**Comment by O-O-Balance** [comment]
Unfortunately, I can't run that example on any of my test devices, including the Moto G5.
I get the following error:

`E/libAR: [error] ARController::androidVideoPush1: ARVideoSource is not running.`

**Comment by O-O-Balance** [comment]
Having run another test on the Moto G5, I have to say I am a bit confused. My app worked fine this time.
This makes the problem intermittent. It also occurred on a HUAWEI phone, just once.
Closing the issue since the problem is different than I assumed.
