### ISSUE TITLE
Android SDK missing assert_ndk_version when run build.sh

### ISSUE THREAD

**Issue by tyoli** [artoolkitx/artoolkit5#152]
Working from directory "/opt/arlab/android".
make: jni/assert_ndk_version.sh: Command not found
ARToolKit5 Android MK file (armeabi-v7a)
make: jni/assert_ndk_version.sh: Command not found
ARToolKit5 Android MK file (x86)
make: jni/assert_ndk_version.sh: Command not found
ARToolKit5 Android MK file (arm64-v8a)
Android NDK: NEON support is only possible for armeabi-v7a ABI  its variant armeabi-v7a-hard and x86 ABI   
Android NDK: Please add checks against TARGET_ARCH_ABI in jni/Android.mk    
/opt/Android_SDK/android-ndk-r10e/build/core/build-binary.mk:292: *** Android NDK: Aborting    .  Stop.

**Comment by ThorstenBux** [comment]
From what I can see it looks like your NDK version is 10. I'd try and update to a more recent version and try again.
