### ISSUE TITLE
how to build arwrapper.dll with vs2015 or vs 2013?

### ISSUE THREAD

**Issue by dragonflyhe** [artoolkitx/artoolkit5#153]
how to build arwrapper.dll with vs2015 or vs 2013?
Is there any other files needed for build arwrapper.dll?  eg. zlib.h...

**Comment by ThorstenBux** [comment]
we have VS 2017 projects that compile directly from the repo or if you download from http://www.artoolkitx.org/ they are working to the best of my knowledge. Never tried VS 2013/15

**Comment by dragonflyhe** [comment]
okey,thank you very much!
