### ISSUE TITLE
i download the android's sdk and when use build_native_examples.sh in ubuntu,it's error.

### ISSUE THREAD

**Issue by tyoli** [artoolkitx/artoolkit5#154]
Working from directory "/opt/arlab/artoolkit-android".
Building on Linux (x86_64)
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/ARSimpleNativeProj/aRSimpleNative
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:ARWrapper: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/libs/armeabi-v7a/libARWrapper.so exists  or that its path is correct   
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/ARSimpleNativeCarsProj/aRSimpleNativeCars
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:ARWrapper: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/libs/armeabi-v7a/libARWrapper.so exists  or that its path is correct   
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/ARNativeES1Proj/aRNativeES1
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:util: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/obj/local/armeabi-v7a/libutil.a exists  or that its path is correct   
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/ARNativeProj/aRNative
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:util: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/obj/local/armeabi-v7a/libutil.a exists  or that its path is correct   
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/ARNativeOSGProj/aRNativeOSG
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:util: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/obj/local/armeabi-v7a/libutil.a exists  or that its path is correct   
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/nftSimpleProj/nftSimple
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:util: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/obj/local/armeabi-v7a/libutil.a exists  or that its path is correct   
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/nftBookProj/nftBook
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:util: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/obj/local/armeabi-v7a/libutil.a exists  or that its path is correct   
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/ARMovieProj/aRMovie
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:util: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/obj/local/armeabi-v7a/libutil.a exists  or that its path is correct   
from /opt/arlab/artoolkit-android: going to AndroidStudioProjects/calib_opticalProj/calib_optical
Android NDK: WARNING: APP_PLATFORM android-15 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-15. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: ERROR:jni/Android.mk:util: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/../../../../../../android/obj/local/armeabi-v7a/libutil.a exists  or that its path is correct

**Comment by ThorstenBux** [comment]
Native examples are not working at the moment. Please try and work with the non-native once.
