### ISSUE TITLE
Camera output not displayed in simpletest compiled with visual studio

### ISSUE THREAD

**Issue by dy-dev** [artoolkitx/artoolkit5#155]
Hello

I have been able to build and run the "simple" project with visual studio but all i get is a greyed window instead of the camera output. The strange part is that when i press "d" ( which switches the application in a debug mode) the image appear in luma mode ( only white and black ) and when I present the marker both in normal and  debug mode the cube is shown, which means that even if the image is not displayed, it is retreived and analysed correctly.
The Configure-win32.vbs script has modified the config.h in the AR. lib project so that it uses the Windows Media Foundation and I must admit I don't really know where to look
Any help would be greatly appreciated 
Thank you

**Comment by ThorstenBux** [comment]
@dy-dev would you consider switching to artoolkitX https://github.com/artoolkitx/artoolkitx ?

**Comment by dy-dev** [comment]
Is it in a state stable enough? If yes, then yeah : I haven't developped on ARToolkit long enough to loose any work in switching so it is something worth considering especially if artoolkit will no longer be maintained

**Comment by ThorstenBux** [comment]
We have run a lot of tests to make it stable. However, you would be one of the early users and help us a lot improving it.
Currently, we don't have the resources to deeply investigate into ARToolKit 5.4 (or earlier) issues.

**Comment by dy-dev** [comment]
I'll give it a try as soon as I have a bit of spare time then. Thank you :)
