### ISSUE TITLE
R & D team can share the old website's code ?

### ISSUE THREAD

**Issue by tyoli** [artoolkitx/artoolkit5#156]
Scientists can share the latest R & D team web site source artoolkit.org website before closing, I want to build a copy of the now abandoned old website for everyone to use, because there are many worthy of our reference to the wiki, including the final stability can be used to download the source code. Thank you very much for the scientists of the R & D team!

**Comment by philip-lamb** [comment]
We don't have access to that site anymore, although the documentation wiki is still available here: https://github.com/artoolkit/artoolkit-docs
