### ISSUE TITLE
There is no AR/config.h for c++ project to include

### ISSUE THREAD

**Issue by snowymo** [artoolkitx/artoolkit5#164]
There are so many `#include <AR/config.h> ` among various files. However, there is no AR/config.h but only AR/config.h.in. I don't understand what does that mean.

**Comment by philip-lamb** [comment]
AR/config.h is generated by running the ./Configure script. This should be done automatically for Windows and macOS builds, but must be done manually on Linux.

**Comment by snowymo** [comment]
What do u mean by automatically?

There is no installation so I directly open the solution for.
