### ISSUE TITLE
android run nftBookProj fail

### ISSUE THREAD

**Issue by Len-jidong** [artoolkitx/artoolkit5#168]
This is my first attempt to use artoolkitx，Encountered several problems，I want someone to help me.
When running nftBookProj，Program crulling prompted me “couldn't find "c++shared.so"” According to experience, I use android-->build.sh generate c++shared.so；but Unable to generate 
 “libnftBookNative.so"  ；
`
09-04 15:29:30.995 11380-11380/org.artoolkit.ar.samples.NftBook E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.artoolkit.ar.samples.NftBook, PID: 11380
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.NftBook-1/base.apk"],nativeLibraryDirectories=[/data/app/org.artoolkit.ar.samples.NftBook-1/lib/arm64, /data/app/org.artoolkit.ar.samples.NftBook-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libnftBookNative.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at org.artoolkit.ar.samples.nftBook.nftBookActivity.<clinit>(nftBookActivity.java:88)`

**Comment by 13311183035** [comment]
who can help me ,thanks

**Comment by itk0492** [comment]
I couldn't make it work either, but I achieved to make it work with ARToolKit 5.3.3, so maybe you can download that version and try to run it.

**Comment by Len-jidong** [comment]
thanks！

so...I will not use this again.
