### ISSUE TITLE
The README mentions an executable binary for windows installation, but I can't seem to find them anywhere.

### ISSUE THREAD

**Issue by yongpan0715** [artoolkitx/artoolkit5#177]
The README mentions an executable binary for windows installation, but I can't seem to find them anywhere.
thanks

**Comment by kalwalt** [comment]
Ho @yongpan0715  you should go to downloads at [artoolkitx.org](https://artoolkitx.org)

**Comment by killatsignlife** [comment]
@kalwalt this site doesn't exist anymore. Has another alternative?

**Comment by philip-lamb** [comment]
@LeiteSS https://www.artoolkitx.org/docs/downloads/
