### ISSUE TITLE
2d barcode marker generator code and 2d marker future

### ISSUE THREAD

**Issue by yichuan1118** [artoolkitx/artoolkit5#7]
Hi,

I'm aware there is a PHP website to generate 2d barcode like 5x5, 6x6 etc. Is there any source code available to generate 2d barcode in the repo?

Is there any plan to support other 2d code that can encode information in it? (Similar to QR code, VuMark, etc.)

Thank you!

**Comment by yichuan1118** [comment]
A javascript compile of artoolkit actually support QR code now: https://medium.com/arjs/ar-code-a-fast-path-to-augmented-reality-60e51be3cbdf

**Comment by ThorstenBux** [comment]
Nice that you like the JSQRcode. Be aware that that is not native ARToolKit but ar-js. 
Regarding your questions, yes we have plans but they are not very concrete at this stage
