### ISSUE TITLE
Increase MAX_PAGES 64 to 1024 in arcontroller.h 

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#90]
<a href="https://github.com/VladVuk"><img src="https://avatars0.githubusercontent.com/u/8056983?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [VladVuk](https://github.com/VladVuk)**
_Wednesday May 24, 2017 at 22:16 GMT_
_Originally opened as https://github.com/artoolkit/artoolkit5/issues/310_

----

What is needed to be changed in arwrapper before recompiling artoolkit for android to GET ability of Loading more than 64 NFT Markers?

**Comment by ThorstenBux** [comment]
<a href="https://github.com/Neuroforge"><img src="https://avatars3.githubusercontent.com/u/1474186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Neuroforge](https://github.com/Neuroforge)**
_Saturday May 27, 2017 at 10:53 GMT_

----

I'd wait 2-3 weeks for ARToolkit6 that is optimized for 100s of images using the new 2D Planar Tracker class. It's amazing compared to old NFT stuff. I feel that the wait would be beneficial as the interface allows for loading of entire image databases.

Are you having trouble adding more than 64 NFT markers? Is there any error output? 

I know the 3 x 3 codes have a limits due to the way they work.

"These matrix-code markers are a 3x3 format without error detection or correction, allowing up to 64 different markers to be identified."

Regards,

Daniel

**Comment by ThorstenBux** [comment]
<a href="https://github.com/VladVuk"><img src="https://avatars0.githubusercontent.com/u/8056983?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [VladVuk](https://github.com/VladVuk)**
_Thursday Oct 05, 2017 at 11:53 GMT_

----

Hello Neuroforge & ThorstenBux,

I have been waiting for ARToolkit6 but unfortunately it is still not available in production version.

It seems to me that ARTookit 5 is simple to recompile and I need your help.

Please explain what is needed to be modified in the code for ARWrapper (ARBaseLib) in order to have more than 64 NFT markers in active set ? 
There are limits somewhere in arcontroller.h or else by which after 64 added markers addMarker() return false!

I will have markers with single PAGE but you can include Pages into explanation as well.

I need possibility to have ~1024 markers added into the same active recognition set.

Best Regards,
Vlad

**Comment by ThorstenBux** [comment]
<a href="https://github.com/VladVuk"><img src="https://avatars0.githubusercontent.com/u/8056983?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [VladVuk](https://github.com/VladVuk)**
_Tuesday Oct 10, 2017 at 16:42 GMT_

----

Guys, this is really problematic issue.

When I increase MAX_PAGES to 1024 and addMarkers() call 65x times it returns that all markers are added but when it start NFT tracking thread it fails! 
Each time!

So please explain which else constants needs to be increased to 1024 as there are 695 search/found " 64" in *.c;*.cpp;*.h;*.hpp files.

**Comment by VladVuk** [comment]
I succeedded to increase IT.
Issue was that ALL already built .o files needed to be deleted before
compiling.

ned, 28. sij 2018. u 23:45 Thorsten Bux <notifications@github.com> napisao
je:

**Comment by ThorstenBux** [comment]
Thanks @VladVuk
