### ISSUE TITLE
Wrong colors on Raspberry Pi

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#94]
<a href="https://github.com/jordan314"><img src="https://avatars3.githubusercontent.com/u/1194589?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jordan314](https://github.com/jordan314)**
_Thursday Jun 08, 2017 at 06:30 GMT_
_Originally opened as https://github.com/artoolkit/artoolkit5/issues/319_

----

Hi,
I got ARToolkit compiling on my raspberry pi 3 with these flags:
```
CC=gcc
LDFLAG=-L/usr/lib/i386-linux-gnu -L/usr/lib -L$(LIB_DIR)/linux-armv7l -L$(LIB_DIR)
LIBS= -lARgsub_lite -lARvideo -lAR -lARICP -lAR -lglut -lGLU -lGL -lX11 -lm -lpthread -ljpeg
CFLAG= -O3 -fPIC -mcpu=cortex-a53 -mfpu=neon-vfpv4 -DHAVE_NFT=1 -I/usr/include/i386-linux-gnu -I$(INC_DIR)
```

But my video output looks hot pink. I'm thinking I have the wrong color palette, like maybe it's not converting YUV to RGB.
I'm using Video4Linux2 and I know that my camera works ok (I've tried both a logitech USB web camera and a pi camera). This is what a normal photo looks using raspistill or mplayer:
https://artoolkit.org/community/forums/download/file.php?id=391&sid=2c875a4ef6996ae007da4cccf6b44fa1

But when I run simpleLite, this is what the same view looks like:
https://artoolkit.org/community/forums/download/file.php?id=393&sid=2c875a4ef6996ae007da4cccf6b44fa1

Here is the command I'm running:
```
./simpleTest -device=LinuxV4L2 -saturation=0 -contrast=0 -hue=0
```

if I try -palette=YUV420P the video window never loads.
```
./simpleTest -device=LinuxV4L2 -saturation=0 -contrast=0 -hue=0 -palette=YUV420P
```
Anyone have any ideas? Thanks

**Comment by ThorstenBux** [comment]
<a href="https://github.com/jordan314"><img src="https://avatars3.githubusercontent.com/u/1194589?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jordan314](https://github.com/jordan314)**
_Tuesday Jun 13, 2017 at 04:41 GMT_

----

I posted a bounty for this issue here:
https://www.bountysource.com/issues/46007465-wrong-colors-on-raspberry-pi

**Comment by ThorstenBux** [comment]
@jordan314 have you solved that yet? Would be good to have PI support with artoolkit5

Closing as quite old and no response recently so I assume it has been solved. Please reopen if needed.

**Comment by jordan314** [comment]
I switched to aruco/openCV because I couldn't solve this, but a user on the raspberry pi forums suggested using V4L instead of V4L2. https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=181389&p=1266015

**Comment by ThorstenBux** [comment]
@jordan314 sad to hear that it was not solvable. Thanks for posting a possible lead for others to follow.
